apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_role = Viewer

    [dashboards]
    default_home_dashboard_path = /etc/grafana/provisioning/dashboards/mlops-dashboard.json

    [datasources]
    datasources.yaml: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server:80
          isDefault: true 