apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'fastapi'
        static_configs:
          - targets: ['fastapi:8000']

      - job_name: 'mlflow'
        static_configs:
          - targets: ['mlflow:5000']

      - job_name: 'airflow'
        static_configs:
          - targets: ['airflow-webserver:8080'] 