apiVersion: v1
kind: Service
metadata:
  name: clean-data-db
spec:
  ports:
  - port: 5432
    name: postgresql
  selector:
    app: clean-data-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clean-data-db-config
data:
  POSTGRES_DB: clean_data
  POSTGRES_USER: cleandata
  POSTGRES_PASSWORD: cleandata123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clean-data-db
spec:
  serviceName: clean-data-db
  replicas: 1
  selector:
    matchLabels:
      app: clean-data-db
  template:
    metadata:
      labels:
        app: clean-data-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
          name: postgresql
        envFrom:
        - configMapRef:
            name: clean-data-db-config
        volumeMounts:
        - name: clean-data-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: clean-data-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi 