apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"airflow-webserver","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"airflow-webserver"}},"template":{"metadata":{"labels":{"app":"airflow-webserver"}},"spec":{"containers":[{"args":["-c","pip install --no-cache-dir -r /requirements/requirements.txt\nairflow db migrate\nairflow webserver\n"],"command":["/bin/bash"],"env":[{"name":"AIRFLOW__CORE__SQL_ALCHEMY_CONN","value":"postgresql://airflow:airflow@postgresql:5432/airflow"},{"name":"AIRFLOW__CORE__EXECUTOR","value":"LocalExecutor"},{"name":"AIRFLOW__WEBSERVER__SECRET_KEY","value":"your_secret_key_here"},{"name":"AIRFLOW__WEBSERVER__EXPOSE_CONFIG","value":"True"},{"name":"AIRFLOW__WEBSERVER__AUTHENTICATE","value":"False"}],"image":"apache/airflow:2.7.1","name":"webserver","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/opt/airflow/dags","name":"dags"},{"mountPath":"/requirements","name":"requirements"}]}],"volumes":[{"configMap":{"name":"airflow-dags"},"name":"dags"},{"configMap":{"name":"airflow-requirements"},"name":"requirements"}]}}}}
  creationTimestamp: "2025-06-01T00:40:35Z"
  generation: 6
  name: airflow-webserver
  namespace: default
  resourceVersion: "14143"
  uid: ad4a93e8-c629-4795-be05-1bd57c28e59b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airflow-webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: webserver
        image: apache/airflow:2.7.1
        ports:
        - containerPort: 8080
        command: ["/bin/bash"]
        args:
        - -c
        - |
          pip install --no-cache-dir -r /requirements/requirements.txt
          airflow db migrate
          airflow webserver
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: postgresql://airflow:airflow@postgresql:5432/airflow
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: your_secret_key_here
        - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
          value: "True"
        - name: AIRFLOW__WEBSERVER__AUTHENTICATE
          value: "False"
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: requirements
          mountPath: /requirements
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dags
        configMap:
          name: airflow-dags
      - name: requirements
        configMap:
          name: airflow-requirements
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-01T00:40:35Z"
    lastUpdateTime: "2025-06-01T02:09:55Z"
    message: ReplicaSet "airflow-webserver-68f478cc54" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-01T02:14:11Z"
    lastUpdateTime: "2025-06-01T02:14:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
