apiVersion: v1
kind: PersistentVolume
metadata:
  name: raw-data-pv
  namespace: mlops
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/estudiante/Proyecto Final MLOPS/data/raw
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-data-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi 