apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-init
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-init
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-init
subjects:
- kind: ServiceAccount
  name: airflow-init
roleRef:
  kind: Role
  name: airflow-init
  apiGroup: rbac.authorization.k8s.io 