apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: mlops
spec:
  selector:
    app: airflow-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 