apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  ports:
  - port: 5000
    targetPort: mlflow
    protocol: TCP
    name: http
  selector:
    app: mlflow
  type: ClusterIP 