apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 8000
      - path: /mlflow
        pathType: Prefix
        backend:
          service:
            name: mlflow
            port:
              number: 5000
      - path: /airflow
        pathType: Prefix
        backend:
          service:
            name: airflow-webserver
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamlit
            port:
              number: 8501 