apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  ports:
  - port: 8501
    name: streamlit
  selector:
    app: streamlit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: zafrar09/streamlit:latest
        ports:
        - containerPort: 8501
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: FASTAPI_URL
          value: "http://fastapi:8000" 