apiVersion: v1
kind: Service
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: streamlit 