apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fastapi
  type: ClusterIP 