apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgresql:5432/airflow"
  AIRFLOW__WEBSERVER__SECRET_KEY: "your-secret-key-here"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs" 