name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  MLFLOW_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mlflow
  FASTAPI_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi
  STREAMLIT_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest tests/ -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Docker Hub Credentials
        run: |
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DockerHub username is set"
          else
            echo "DockerHub username is NOT set"
            exit 1
          fi
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DockerHub token is set"
          else
            echo "DockerHub token is NOT set"
            exit 1
          fi
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Build and push MLflow image
      - name: Build and push MLflow
        uses: docker/build-push-action@v4
        with:
          context: ./mlflow
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.MLFLOW_IMAGE }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.MLFLOW_IMAGE }}:latest
          
      # Build and push FastAPI image
      - name: Build and push FastAPI
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FASTAPI_IMAGE }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.FASTAPI_IMAGE }}:latest
          
      # Build and push Streamlit image
      - name: Build and push Streamlit
        uses: docker/build-push-action@v4
        with:
          context: ./streamlit
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.STREAMLIT_IMAGE }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.STREAMLIT_IMAGE }}:latest 